### ISSUE TITLE
Execute Permission

### ISSUE THREAD

**Issue by RastaJedi** [eXhumer/pyTinGen#19]
Thanks for the hashbang! Can you chmod +x TinGen.py? :) If you can do that, then I won't have to ever change anything after a git pull! Thanks man, you rock! TinGen is the best! And if you can't, no big deal :).

**Comment by eXhumer** [comment]
Hello. Thank you for bringing up this issue. The correct fix will be `git update-index --chmod=+x TinGen.py`. I'll push a fix for it with next update.

**Comment by eXhumer** [comment]
Fixed with commit 46c13db.
